import ast
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "pages" / "reports.py"


class ReportsWorkspaceContracts(unittest.TestCase):
    def test_operational_header_and_event_context(self):
        source = PAGE.read_text(encoding="utf-8-sig")
        self.assertIn(
            'title="Situation Reports & Exports"',
            source,
        )
        self.assertIn("render_operational_event_strip(", source)
        self.assertNotIn('st.title("Reports and Exports")', source)

    def test_report_command_picture_and_workspace_tabs(self):
        source = PAGE.read_text(encoding="utf-8-sig")
        self.assertIn('title="Report Command Picture"', source)
        for token in (
            '"Saved Snapshots"',
            '"Provisional"',
            '"Official Validated"',
            '"Latest Snapshot"',
            '"Create Snapshot"',
            '"Snapshot Archive (',
            '"Review & Export"',
        ):
            self.assertIn(token, source)

    def test_snapshot_generation_is_guided_and_semantics_remain(self):
        source = PAGE.read_text(encoding="utf-8-sig")
        for token in (
            'title="Confirm Reporting Context"',
            'title="Choose Data Mode"',
            'title="Authorize Immutable Snapshot"',
            "create_report_snapshot(",
            "generation_key=st.session_state[",
            "generator_user_id=current_user.id",
            "DuplicateReportGenerationError",
            "NoActiveEventForReportError",
            "disabled=not confirmation",
        ):
            self.assertIn(token, source)

    def test_column_write_calls_use_one_element(self):
        source = PAGE.read_text(encoding="utf-8-sig")
        tree = ast.parse(source)

        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "write"
                and isinstance(node.func.value, ast.Subscript)
            ):
                self.assertLessEqual(
                    len(node.args),
                    1,
                    "Column-level write() calls may replace only one element.",
                )

    def test_archive_is_compact_but_integrity_remains_available(self):
        source = PAGE.read_text(encoding="utf-8-sig")
        self.assertIn('title="Snapshot Archive"', source)
        self.assertIn('"Event": display_event_name(row)', source)
        self.assertIn('"SitRep": display_sitrep(', source)
        self.assertNotIn('"Event / SitRep"', source)
        self.assertIn('"Integrity"', source)
        self.assertIn("compact_integrity_hash(", source)
        self.assertIn('st.caption("SHA-256 integrity hash")', source)
        self.assertIn('selected_snapshot["snapshot_sha256"]', source)

        archive_position = source.index("archive_rows = [")
        integrity_position = source.index(
            '"Integrity": compact_integrity_hash(',
            archive_position,
        )
        generator_position = source.index(
            '"Generated By": row["generated_by"]',
            archive_position,
        )
        self.assertLess(integrity_position, generator_position)

    def test_review_and_export_preserve_cache_and_downloads(self):
        source = PAGE.read_text(encoding="utf-8-sig")
        for token in (
            "get_report_snapshot(",
            "get_report_export_bundle(",
            '"Download Excel Workbook"',
            'extension="xlsx"',
            '"Download PDF SitRep"',
            'extension="pdf"',
            "ReportExportCacheError",
        ):
            self.assertIn(token, source)

        self.assertNotIn("compact=True", source)

    def test_historical_exports_remain_without_active_event(self):
        source = PAGE.read_text(encoding="utf-8-sig")
        self.assertIn("if active_event is None:", source)
        self.assertIn(
            "Historical snapshots remain ",
            source,
        )
        self.assertNotIn(
            'if not snapshot_rows:\n    st.info(',
            source,
        )


if __name__ == "__main__":
    unittest.main()
