from __future__ import annotations

from html import escape
from io import BytesIO
import re
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


class ExportServiceError(Exception):
    """Raised when a saved report snapshot cannot be exported."""


def _snapshot(record: dict[str, object]) -> dict[str, object]:
    snapshot = record.get("snapshot_json")

    if not isinstance(snapshot, dict):
        raise ExportServiceError(
            "The selected report snapshot is invalid."
        )

    return snapshot


def _safe(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def _display_event_name(event: dict[str, object]) -> str:
    classification = _safe(
        event.get("classification")
    ).strip()
    name = _safe(
        event.get("event_name")
    ).strip()

    if classification:
        return f"{classification} {name}".strip()

    return name or "Disaster Event"


def report_filename(
    record: dict[str, object],
    *,
    extension: str,
) -> str:
    snapshot = _snapshot(record)
    event = snapshot.get("event") or {}
    event_name = _display_event_name(event)
    sitrep = _safe(
        record.get("sitrep_number")
    ).strip() or "Snapshot"
    mode = _safe(
        record.get("report_mode")
    )
    snapshot_id = int(
        record["id"]
    )

    raw = (
        f"MDRRMO_Naic_{event_name}_{sitrep}_{mode}_"
        f"snapshot_{snapshot_id}.{extension}"
    )

    return re.sub(
        r"[^A-Za-z0-9._-]+",
        "_",
        raw,
    ).strip("_")


def _write_table_sheet(
    workbook: Workbook,
    *,
    title: str,
    headers: list[str],
    rows: list[list[Any]],
) -> None:
    sheet = workbook.create_sheet(
        title=title
    )
    sheet.freeze_panes = "A2"
    sheet.append(headers)

    for row in rows:
        sheet.append(row)

    for cell in sheet[1]:
        cell.font = Font(bold=True)
        cell.alignment = Alignment(
            horizontal="center",
            vertical="center",
            wrap_text=True,
        )

    for row in sheet.iter_rows(
        min_row=2
    ):
        for cell in row:
            cell.alignment = Alignment(
                vertical="top",
                wrap_text=True,
            )

    for column_index, header in enumerate(
        headers,
        start=1,
    ):
        values = [
            _safe(header)
        ]
        values.extend(
            _safe(
                sheet.cell(
                    row=row_number,
                    column=column_index,
                ).value
            )
            for row_number in range(
                2,
                sheet.max_row + 1,
            )
        )

        width = min(
            max(
                max(
                    (len(value) for value in values),
                    default=10,
                ) + 2,
                10,
            ),
            36,
        )

        sheet.column_dimensions[
            get_column_letter(column_index)
        ].width = width

    sheet.auto_filter.ref = sheet.dimensions


def build_excel_report(
    record: dict[str, object],
) -> bytes:
    try:
        snapshot = _snapshot(record)
        event = snapshot.get("event") or {}
        population = snapshot.get("population_summary") or {}
        evacuation = snapshot.get("evacuation_summary") or {}
        reconciliation = snapshot.get("reconciliation_summary") or {}

        workbook = Workbook()
        summary_sheet = workbook.active
        summary_sheet.title = "Executive Summary"

        summary_rows = [
            ["MDRRMO Naic Situation Report", ""],
            ["Snapshot ID", record.get("id")],
            ["Snapshot SHA-256", record.get("snapshot_sha256")],
            ["Report Mode", record.get("report_mode")],
            ["Generated By", record.get("generated_by")],
            ["Generated At", _safe(record.get("generated_at"))],
            ["Event", _display_event_name(event)],
            ["Hazard", event.get("hazard_type")],
            ["Alert Level", event.get("alert_code")],
            ["EOC Status", event.get("eoc_status")],
            ["SitRep Number", record.get("sitrep_number")],
            ["Official Reference", event.get("official_reference")],
            ["Situation Overview", event.get("situation_overview")],
            ["", ""],
            ["Barangays with Affected People", population.get("affected_barangays", 0)],
            ["Affected Families", population.get("affected_families", 0)],
            ["Affected Individuals", population.get("affected_individuals", 0)],
            ["Inside EC Families", population.get("inside_ec_families", 0)],
            ["Inside EC Individuals", population.get("inside_ec_individuals", 0)],
            ["Outside EC Families", population.get("outside_ec_families", 0)],
            ["Outside EC Individuals", population.get("outside_ec_individuals", 0)],
            ["Total Displaced Families", population.get("displaced_families", 0)],
            ["Total Displaced Individuals", population.get("displaced_individuals", 0)],
            ["Affected Families Not Included in Displacement Totals", population.get("affected_not_displaced_families", 0)],
            ["Affected Individuals Not Included in Displacement Totals", population.get("affected_not_displaced_individuals", 0)],
            ["Pending Rescue Requests", population.get("pending_rescue_requests", 0)],
            ["Impassable Roads", population.get("impassable_roads", 0)],
            ["Power Interruptions", population.get("interrupted_power", 0)],
            ["Water Interruptions", population.get("interrupted_water", 0)],
            ["", ""],
            ["Operational ECs", evacuation.get("open_centers", 0)],
            ["EC Registered Families", evacuation.get("families", 0)],
            ["EC Registered Individuals", evacuation.get("individuals", 0)],
            ["EC Safe Capacity", evacuation.get("safe_capacity", 0)],
            ["Over-Capacity ECs", evacuation.get("over_capacity_centers", 0)],
            ["Critical Food", evacuation.get("critical_food", 0)],
            ["Critical Water", evacuation.get("critical_water", 0)],
            ["Medical Cases", evacuation.get("medical_cases", 0)],
            ["", ""],
            ["Barangay Reports Received", population.get("reports_received", 0)],
            ["Barangays Without Reports", population.get("missing_reports", 0)],
            ["Pending Validation", population.get("pending_validation", 0)],
            ["Needs Correction", population.get("needs_correction", 0)],
            ["Reconciliation Matches", reconciliation.get("match", 0)],
            ["Reconciliation Mismatches", reconciliation.get("mismatch", 0)],
            ["Missing Reconciliation Source", reconciliation.get("missing_source", 0)],
            ["Allocation Conflicts", reconciliation.get("allocation_conflict", 0)],
        ]

        for row in summary_rows:
            summary_sheet.append(row)

        summary_sheet["A1"].font = Font(
            bold=True,
            size=16,
        )
        summary_sheet.column_dimensions["A"].width = 38
        summary_sheet.column_dimensions["B"].width = 65

        for row in summary_sheet.iter_rows():
            for cell in row:
                cell.alignment = Alignment(
                    vertical="top",
                    wrap_text=True,
                )

        barangay_headers = [
            "Barangay",
            "Situation",
            "Affected Families",
            "Affected Individuals",
            "Inside EC Families",
            "Inside EC Individuals",
            "Outside EC Families",
            "Outside EC Individuals",
            "Flood",
            "Flood Depth (cm)",
            "Road",
            "Power",
            "Water",
            "Rescue Requests",
            "Validation",
            "Source",
            "Recorded At",
            "Remarks",
        ]

        barangay_rows = [
            [
                row.get("barangay_name"),
                row.get("situation_status"),
                row.get("affected_families"),
                row.get("affected_individuals"),
                row.get("inside_ec_families"),
                row.get("inside_ec_individuals"),
                row.get("outside_ec_families"),
                row.get("outside_ec_individuals"),
                row.get("flood_status"),
                row.get("flood_depth_cm"),
                row.get("road_status"),
                row.get("power_status"),
                row.get("water_status"),
                row.get("rescue_requests"),
                row.get("validation_status"),
                row.get("source"),
                row.get("recorded_at"),
                row.get("remarks"),
            ]
            for row in snapshot.get("barangays", [])
        ]

        _write_table_sheet(
            workbook,
            title="Barangay Situation",
            headers=barangay_headers,
            rows=barangay_rows,
        )

        ec_headers = [
            "Evacuation Center",
            "Barangay",
            "Status",
            "Families",
            "Individuals",
            "Safe Capacity",
            "Children",
            "Senior Citizens",
            "PWD",
            "Pregnant Women",
            "Medical Cases",
            "Food",
            "Water",
            "Electricity",
            "Sanitation",
            "Validation",
            "Source",
            "Recorded At",
            "Remarks",
        ]

        ec_rows = [
            [
                row.get("center_name"),
                row.get("barangay_name"),
                row.get("status"),
                row.get("families"),
                row.get("individuals"),
                row.get("safe_capacity"),
                row.get("children"),
                row.get("senior_citizens"),
                row.get("pwd"),
                row.get("pregnant_women"),
                row.get("medical_cases"),
                row.get("food_status"),
                row.get("water_status"),
                row.get("electricity_status"),
                row.get("sanitation_status"),
                row.get("validation_status"),
                row.get("source"),
                row.get("recorded_at"),
                row.get("remarks"),
            ]
            for row in snapshot.get("evacuation_centers", [])
        ]

        _write_table_sheet(
            workbook,
            title="Evacuation Centers",
            headers=ec_headers,
            rows=ec_rows,
        )

        reconciliation_headers = [
            "Barangay",
            "Status",
            "Barangay Inside EC Families",
            "EC Attributed Families",
            "Family Difference",
            "Barangay Inside EC Individuals",
            "EC Attributed Individuals",
            "Individual Difference",
            "Barangay Report At",
            "Latest EC Source At",
        ]

        reconciliation_rows = [
            [
                row.get("barangay_name"),
                row.get("reconciliation_status"),
                row.get("barangay_inside_families"),
                row.get("ec_inside_families"),
                row.get("family_difference"),
                row.get("barangay_inside_individuals"),
                row.get("ec_inside_individuals"),
                row.get("individual_difference"),
                row.get("barangay_recorded_at"),
                row.get("latest_ec_recorded_at"),
            ]
            for row in snapshot.get("reconciliation", [])
        ]

        _write_table_sheet(
            workbook,
            title="Reconciliation",
            headers=reconciliation_headers,
            rows=reconciliation_rows,
        )

        incident_headers = [
            "Control Number",
            "Barangay",
            "Location",
            "Type",
            "Description",
            "Priority",
            "Persons Affected",
            "Status",
            "Assigned Team",
            "Assigned Vehicle",
            "Action Taken",
            "Source",
            "Validation",
            "Reported By",
            "Reported At",
            "Updated At",
            "Resolved At",
        ]

        incident_rows = [
            [
                row.get("control_number"),
                row.get("barangay_name"),
                row.get("exact_location"),
                row.get("incident_type"),
                row.get("description"),
                row.get("priority"),
                row.get("persons_affected"),
                row.get("status"),
                row.get("assigned_team"),
                row.get("assigned_vehicle"),
                row.get("action_taken"),
                row.get("source"),
                row.get("validation_status"),
                row.get("reported_by"),
                row.get("reported_at"),
                row.get("updated_at"),
                row.get("resolved_at"),
            ]
            for row in snapshot.get("incidents", [])
        ]

        _write_table_sheet(
            workbook,
            title="Incident Log",
            headers=incident_headers,
            rows=incident_rows,
        )

        metadata_sheet = workbook.create_sheet(
            title="Snapshot Metadata"
        )
        metadata_rows = [
            ["Field", "Value"],
            ["Snapshot ID", record.get("id")],
            ["Event ID", record.get("event_id")],
            ["Generation Key", record.get("generation_key")],
            ["Report Type", record.get("report_type")],
            ["Report Mode", record.get("report_mode")],
            ["SitRep Number", record.get("sitrep_number")],
            ["Generated By", record.get("generated_by")],
            ["Generated At", _safe(record.get("generated_at"))],
            ["Snapshot SHA-256", record.get("snapshot_sha256")],
            ["Snapshot Schema Version", snapshot.get("schema_version")],
        ]

        for row in metadata_rows:
            metadata_sheet.append(row)

        metadata_sheet["A1"].font = Font(bold=True)
        metadata_sheet["B1"].font = Font(bold=True)
        metadata_sheet.column_dimensions["A"].width = 28
        metadata_sheet.column_dimensions["B"].width = 80

        output = BytesIO()
        workbook.save(output)
        return output.getvalue()

    except ExportServiceError:
        raise
    except Exception as error:
        raise ExportServiceError(
            "The Excel report could not be generated."
        ) from error


def _pdf_table(
    headers: list[str],
    rows: list[list[Any]],
    *,
    column_widths: list[float] | None = None,
    font_size: float = 6.5,
) -> Table:
    if column_widths is None:
        usable_width = landscape(A4)[0] - (20 * mm)
        column_widths = [
            usable_width / len(headers)
            for _ in headers
        ]

    header_style = ParagraphStyle(
        "ReportTableHeader",
        fontName="Helvetica-Bold",
        fontSize=font_size,
        leading=font_size + 1.5,
    )
    cell_style = ParagraphStyle(
        "ReportTableCell",
        fontName="Helvetica",
        fontSize=font_size,
        leading=font_size + 1.5,
    )

    data = [
        [
            Paragraph(escape(_safe(value)), header_style)
            for value in headers
        ]
    ]
    data.extend(
        [
            [
                Paragraph(escape(_safe(value)), cell_style)
                for value in row
            ]
            for row in rows
        ]
    )

    table = Table(
        data,
        colWidths=column_widths,
        repeatRows=1,
        hAlign="LEFT",
    )
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("LEFTPADDING", (0, 0), (-1, -1), 2),
                ("RIGHTPADDING", (0, 0), (-1, -1), 2),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )
    return table


def build_pdf_report(
    record: dict[str, object],
) -> bytes:
    try:
        snapshot = _snapshot(record)
        event = snapshot.get("event") or {}
        population = snapshot.get("population_summary") or {}
        evacuation = snapshot.get("evacuation_summary") or {}
        reconciliation = snapshot.get("reconciliation_summary") or {}

        output = BytesIO()
        document = SimpleDocTemplate(
            output,
            pagesize=landscape(A4),
            rightMargin=10 * mm,
            leftMargin=10 * mm,
            topMargin=10 * mm,
            bottomMargin=12 * mm,
            title="MDRRMO Naic Situation Report",
            author=_safe(record.get("generated_by")),
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "MDRRMOTitle",
            parent=styles["Title"],
            alignment=TA_CENTER,
            fontSize=16,
            leading=19,
            spaceAfter=8,
        )
        heading_style = ParagraphStyle(
            "MDRRMOHeading",
            parent=styles["Heading2"],
            fontSize=11,
            leading=13,
            spaceBefore=6,
            spaceAfter=4,
        )
        body_style = ParagraphStyle(
            "MDRRMOBody",
            parent=styles["BodyText"],
            fontSize=8.5,
            leading=11,
        )

        story = [
            Paragraph(
                "MDRRMO NAIC SITUATION REPORT",
                title_style,
            ),
            Paragraph(
                escape(
                    f"{_display_event_name(event)} | "
                    f"{_safe(event.get('alert_code'))} Alert | "
                    f"EOC: {_safe(event.get('eoc_status'))}"
                ),
                body_style,
            ),
            Paragraph(
                escape(
                    f"Report mode: {_safe(record.get('report_mode'))} | "
                    f"SitRep: {_safe(record.get('sitrep_number')) or 'Not set'} | "
                    f"Generated: {_safe(record.get('generated_at'))}"
                ),
                body_style,
            ),
            Paragraph(
                escape(
                    f"Generated by: {_safe(record.get('generated_by'))}"
                ),
                body_style,
            ),
            Paragraph(
                escape(
                    f"Snapshot ID: {_safe(record.get('id'))} | "
                    f"SHA-256: {_safe(record.get('snapshot_sha256'))}"
                ),
                body_style,
            ),
            Spacer(1, 4 * mm),
        ]

        overview = _safe(
            event.get("situation_overview")
        ).strip()
        reference = _safe(
            event.get("official_reference")
        ).strip()

        if reference:
            story.append(
                Paragraph(
                    escape(
                        f"Official reference: {reference}"
                    ),
                    body_style,
                )
            )

        if overview:
            story.extend(
                [
                    Paragraph(
                        "Situation Overview",
                        heading_style,
                    ),
                    Paragraph(
                        escape(overview),
                        body_style,
                    ),
                ]
            )

        story.append(
            Paragraph(
                "Operational Summary",
                heading_style,
            )
        )

        summary_rows = [
            [
                "Barangays with Affected People",
                population.get("affected_barangays", 0),
                "Affected Families",
                population.get("affected_families", 0),
                "Affected Individuals",
                population.get("affected_individuals", 0),
            ],
            [
                "Inside EC Families",
                population.get("inside_ec_families", 0),
                "Inside EC Individuals",
                population.get("inside_ec_individuals", 0),
                "Operational ECs",
                evacuation.get("open_centers", 0),
            ],
            [
                "Outside EC Families",
                population.get("outside_ec_families", 0),
                "Outside EC Individuals",
                population.get("outside_ec_individuals", 0),
                "Over-Capacity ECs",
                evacuation.get("over_capacity_centers", 0),
            ],
            [
                "Rescue Requests",
                population.get("pending_rescue_requests", 0),
                "Impassable Roads",
                population.get("impassable_roads", 0),
                "Medical Cases",
                evacuation.get("medical_cases", 0),
            ],
        ]

        story.append(
            _pdf_table(
                ["Metric", "Value", "Metric", "Value", "Metric", "Value"],
                summary_rows,
                column_widths=[36 * mm, 18 * mm] * 3,
                font_size=8,
            )
        )

        story.append(
            Paragraph(
                "Reporting and Data Quality",
                heading_style,
            )
        )

        quality_rows = [
            [
                population.get("reports_received", 0),
                population.get("missing_reports", 0),
                population.get("pending_validation", 0),
                population.get("needs_correction", 0),
                reconciliation.get("mismatch", 0),
                reconciliation.get("missing_source", 0),
                reconciliation.get("allocation_conflict", 0),
            ]
        ]

        story.append(
            _pdf_table(
                [
                    "Barangay Reports",
                    "Missing Barangays",
                    "Pending Validation",
                    "Needs Correction",
                    "Mismatches",
                    "Missing Source",
                    "Allocation Conflicts",
                ],
                quality_rows,
                font_size=7.5,
            )
        )

        story.append(PageBreak())
        story.append(
            Paragraph(
                "Barangay Situation",
                heading_style,
            )
        )

        barangay_rows = [
            [
                row.get("barangay_name"),
                row.get("situation_status"),
                row.get("affected_families"),
                row.get("affected_individuals"),
                row.get("inside_ec_individuals"),
                row.get("outside_ec_individuals"),
                row.get("flood_status"),
                row.get("road_status"),
                row.get("power_status"),
                row.get("water_status"),
                row.get("rescue_requests"),
                row.get("validation_status"),
            ]
            for row in snapshot.get("barangays", [])
        ]

        story.append(
            _pdf_table(
                [
                    "Barangay",
                    "Situation",
                    "Aff Fam",
                    "Aff Ind",
                    "Inside EC",
                    "Outside EC",
                    "Flood",
                    "Road",
                    "Power",
                    "Water",
                    "Rescue",
                    "Validation",
                ],
                barangay_rows,
                font_size=6.2,
            )
        )

        story.append(PageBreak())
        story.append(
            Paragraph(
                "Evacuation Centers",
                heading_style,
            )
        )

        ec_rows = [
            [
                row.get("center_name"),
                row.get("barangay_name"),
                row.get("status"),
                row.get("families"),
                row.get("individuals"),
                row.get("safe_capacity"),
                row.get("food_status"),
                row.get("water_status"),
                row.get("electricity_status"),
                row.get("medical_cases"),
                row.get("validation_status"),
            ]
            for row in snapshot.get("evacuation_centers", [])
        ]

        story.append(
            _pdf_table(
                [
                    "Center",
                    "Barangay",
                    "Status",
                    "Families",
                    "Individuals",
                    "Capacity",
                    "Food",
                    "Water",
                    "Electricity",
                    "Medical",
                    "Validation",
                ],
                ec_rows,
                font_size=6.4,
            )
        )

        problem_reconciliation = [
            row
            for row in snapshot.get("reconciliation", [])
            if row.get("reconciliation_status")
            not in {"Match", "No Current Data"}
        ]

        if problem_reconciliation:
            story.append(PageBreak())
            story.append(
                Paragraph(
                    "Population Reconciliation Issues",
                    heading_style,
                )
            )

            reconciliation_rows = [
                [
                    row.get("barangay_name"),
                    row.get("reconciliation_status"),
                    row.get("barangay_inside_families"),
                    row.get("ec_inside_families"),
                    row.get("family_difference"),
                    row.get("barangay_inside_individuals"),
                    row.get("ec_inside_individuals"),
                    row.get("individual_difference"),
                ]
                for row in problem_reconciliation
            ]

            story.append(
                _pdf_table(
                    [
                        "Barangay",
                        "Status",
                        "Barangay Fam",
                        "EC Fam",
                        "Fam Diff",
                        "Barangay Ind",
                        "EC Ind",
                        "Ind Diff",
                    ],
                    reconciliation_rows,
                    font_size=7,
                )
            )

        incidents = snapshot.get("incidents", [])

        if incidents:
            story.append(PageBreak())
            story.append(
                Paragraph(
                    "Incident Log",
                    heading_style,
                )
            )

            incident_rows = [
                [
                    row.get("control_number"),
                    row.get("barangay_name"),
                    row.get("incident_type"),
                    row.get("priority"),
                    row.get("status"),
                    row.get("persons_affected"),
                    row.get("exact_location"),
                    row.get("reported_at"),
                ]
                for row in incidents
            ]

            story.append(
                _pdf_table(
                    [
                        "Control",
                        "Barangay",
                        "Type",
                        "Priority",
                        "Status",
                        "Persons",
                        "Location",
                        "Reported At",
                    ],
                    incident_rows,
                    font_size=6.5,
                )
            )

        story.append(
            Spacer(1, 4 * mm)
        )
        story.append(
            Paragraph(
                "This document was generated from an immutable database "
                "snapshot. Generate a new snapshot for later corrections "
                "or updates; do not overwrite an issued snapshot.",
                body_style,
            )
        )

        document.build(story)
        return output.getvalue()

    except ExportServiceError:
        raise
    except Exception as error:
        raise ExportServiceError(
            "The PDF report could not be generated."
        ) from error
