"""link barangay reviews to app users

Revision ID: 8e3e8bf10bb0
Revises: e0d0a553df01
Create Date: 2026-08-09 12:00:05.929238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3e8bf10bb0'
down_revision: Union[str, Sequence[str], None] = 'e0d0a553df01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barangay_updates', sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_barangay_updates_reviewed_by_user_id'), 'barangay_updates', ['reviewed_by_user_id'], unique=False)
    op.create_foreign_key(None, 'barangay_updates', 'app_users', ['reviewed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'barangay_updates', type_='foreignkey')
    op.drop_index(op.f('ix_barangay_updates_reviewed_by_user_id'), table_name='barangay_updates')
    op.drop_column('barangay_updates', 'reviewed_by_user_id')
    # ### end Alembic commands ###
