"""create core disaster monitoring tables

Revision ID: c81ff3be60f6
Revises: 
Create Date: 2026-08-05 11:08:55.989329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81ff3be60f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('barangays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psgc_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('psgc_code')
    )
    op.create_table('disaster_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.Column('hazard_type', sa.String(length=50), nullable=False),
    sa.Column('current_alert_level_id', sa.Integer(), nullable=False),
    sa.Column('eoc_status', sa.String(length=30), server_default='Monitoring', nullable=False),
    sa.Column('current_sitrep_number', sa.String(length=30), nullable=True),
    sa.Column('official_reference', sa.String(length=255), nullable=True),
    sa.Column('situation_overview', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            eoc_status IN (\n                'Monitoring',\n                'Partially Activated',\n                'Activated',\n                'Stand Down'\n            )\n            ", name='ck_disaster_events_eoc_status'),
    sa.ForeignKeyConstraint(['current_alert_level_id'], ['alert_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disaster_events_current_alert_level_id'), 'disaster_events', ['current_alert_level_id'], unique=False)
    op.create_table('evacuation_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('safe_capacity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('safe_capacity >= 0', name='ck_evacuation_centers_capacity'),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'barangay_id', name='uq_evacuation_centers_name_barangay')
    )
    op.create_index(op.f('ix_evacuation_centers_barangay_id'), 'evacuation_centers', ['barangay_id'], unique=False)
    op.create_table('alert_level_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('previous_alert_level_id', sa.Integer(), nullable=True),
    sa.Column('new_alert_level_id', sa.Integer(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authority_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_alert_level_id'], ['alert_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_alert_level_id'], ['alert_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_level_history_event_id'), 'alert_level_history', ['event_id'], unique=False)
    op.create_table('barangay_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=False),
    sa.Column('situation_status', sa.String(length=20), nullable=False),
    sa.Column('affected_families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('affected_individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inside_ec_families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inside_ec_individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outside_ec_families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outside_ec_individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('flood_status', sa.String(length=30), server_default='Unknown', nullable=False),
    sa.Column('flood_depth_cm', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('road_status', sa.String(length=50), server_default='Unknown', nullable=False),
    sa.Column('power_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('water_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('rescue_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('validation_status', sa.String(length=30), server_default='Submitted', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            power_status IN (\n                'Unknown',\n                'Normal',\n                'Partial',\n                'Interrupted'\n            )\n            ", name='ck_barangay_updates_power_status'),
    sa.CheckConstraint("\n            road_status IN (\n                'Unknown',\n                'Passable',\n                'Passable to Large Vehicles Only',\n                'Limited Access',\n                'Impassable'\n            )\n            ", name='ck_barangay_updates_road_status'),
    sa.CheckConstraint("\n            situation_status IN (\n                'No Report',\n                'Normal',\n                'Monitoring',\n                'Affected',\n                'Critical'\n            )\n            ", name='ck_barangay_updates_situation_status'),
    sa.CheckConstraint("\n            validation_status IN (\n                'Draft',\n                'Submitted',\n                'For Validation',\n                'Validated',\n                'Needs Correction',\n                'Superseded'\n            )\n            ", name='ck_barangay_updates_validation_status'),
    sa.CheckConstraint("\n            water_status IN (\n                'Unknown',\n                'Normal',\n                'Partial',\n                'Interrupted'\n            )\n            ", name='ck_barangay_updates_water_status'),
    sa.CheckConstraint('\n            affected_families >= 0\n            AND affected_individuals >= 0\n            AND inside_ec_families >= 0\n            AND inside_ec_individuals >= 0\n            AND outside_ec_families >= 0\n            AND outside_ec_individuals >= 0\n            AND flood_depth_cm >= 0\n            AND rescue_requests >= 0\n            ', name='ck_barangay_updates_nonnegative_counts'),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barangay_updates_barangay_id'), 'barangay_updates', ['barangay_id'], unique=False)
    op.create_index(op.f('ix_barangay_updates_event_id'), 'barangay_updates', ['event_id'], unique=False)
    op.create_index(op.f('ix_barangay_updates_recorded_at'), 'barangay_updates', ['recorded_at'], unique=False)
    op.create_table('evacuation_center_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('evacuation_center_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('children', sa.Integer(), server_default='0', nullable=False),
    sa.Column('senior_citizens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pwd', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pregnant_women', sa.Integer(), server_default='0', nullable=False),
    sa.Column('medical_cases', sa.Integer(), server_default='0', nullable=False),
    sa.Column('food_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('water_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('electricity_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('sanitation_status', sa.String(length=50), server_default='Unknown', nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('validation_status', sa.String(length=30), server_default='Submitted', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            electricity_status IN (\n                'Unknown',\n                'Available',\n                'Partial',\n                'Unavailable'\n            )\n            ", name='ck_evacuation_updates_electricity_status'),
    sa.CheckConstraint("\n            food_status IN (\n                'Unknown',\n                'Sufficient',\n                'Low',\n                'Critical',\n                'Unavailable'\n            )\n            ", name='ck_evacuation_updates_food_status'),
    sa.CheckConstraint("\n            status IN (\n                'Standby',\n                'Open',\n                'Full',\n                'Over Capacity',\n                'Closed'\n            )\n            ", name='ck_evacuation_updates_status'),
    sa.CheckConstraint("\n            validation_status IN (\n                'Draft',\n                'Submitted',\n                'For Validation',\n                'Validated',\n                'Needs Correction',\n                'Superseded'\n            )\n            ", name='ck_evacuation_updates_validation_status'),
    sa.CheckConstraint("\n            water_status IN (\n                'Unknown',\n                'Sufficient',\n                'Low',\n                'Critical',\n                'Unavailable'\n            )\n            ", name='ck_evacuation_updates_water_status'),
    sa.CheckConstraint('\n            families >= 0\n            AND individuals >= 0\n            AND children >= 0\n            AND senior_citizens >= 0\n            AND pwd >= 0\n            AND pregnant_women >= 0\n            AND medical_cases >= 0\n            ', name='ck_evacuation_updates_nonnegative_counts'),
    sa.ForeignKeyConstraint(['evacuation_center_id'], ['evacuation_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evacuation_center_updates_evacuation_center_id'), 'evacuation_center_updates', ['evacuation_center_id'], unique=False)
    op.create_index(op.f('ix_evacuation_center_updates_event_id'), 'evacuation_center_updates', ['event_id'], unique=False)
    op.create_index(op.f('ix_evacuation_center_updates_recorded_at'), 'evacuation_center_updates', ['recorded_at'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('control_number', sa.String(length=40), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=False),
    sa.Column('exact_location', sa.String(length=255), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('persons_affected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='Reported', nullable=False),
    sa.Column('assigned_team', sa.String(length=150), nullable=True),
    sa.Column('assigned_vehicle', sa.String(length=100), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('validation_status', sa.String(length=30), server_default='Submitted', nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            priority IN (\n                'Low',\n                'Moderate',\n                'High',\n                'Critical'\n            )\n            ", name='ck_incidents_priority'),
    sa.CheckConstraint("\n            status IN (\n                'Reported',\n                'For Verification',\n                'Verified',\n                'Team Dispatched',\n                'Responding',\n                'Resolved',\n                'Cancelled'\n            )\n            ", name='ck_incidents_status'),
    sa.CheckConstraint("\n            validation_status IN (\n                'Draft',\n                'Submitted',\n                'For Validation',\n                'Validated',\n                'Needs Correction',\n                'Superseded'\n            )\n            ", name='ck_incidents_validation_status'),
    sa.CheckConstraint('persons_affected >= 0', name='ck_incidents_persons_affected'),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'control_number', name='uq_incidents_event_control_number')
    )
    op.create_index(op.f('ix_incidents_barangay_id'), 'incidents', ['barangay_id'], unique=False)
    op.create_index(op.f('ix_incidents_event_id'), 'incidents', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_event_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_barangay_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_evacuation_center_updates_recorded_at'), table_name='evacuation_center_updates')
    op.drop_index(op.f('ix_evacuation_center_updates_event_id'), table_name='evacuation_center_updates')
    op.drop_index(op.f('ix_evacuation_center_updates_evacuation_center_id'), table_name='evacuation_center_updates')
    op.drop_table('evacuation_center_updates')
    op.drop_index(op.f('ix_barangay_updates_recorded_at'), table_name='barangay_updates')
    op.drop_index(op.f('ix_barangay_updates_event_id'), table_name='barangay_updates')
    op.drop_index(op.f('ix_barangay_updates_barangay_id'), table_name='barangay_updates')
    op.drop_table('barangay_updates')
    op.drop_index(op.f('ix_alert_level_history_event_id'), table_name='alert_level_history')
    op.drop_table('alert_level_history')
    op.drop_index(op.f('ix_evacuation_centers_barangay_id'), table_name='evacuation_centers')
    op.drop_table('evacuation_centers')
    op.drop_index(op.f('ix_disaster_events_current_alert_level_id'), table_name='disaster_events')
    op.drop_table('disaster_events')
    op.drop_table('barangays')
    op.drop_table('alert_levels')
    # ### end Alembic commands ###
