"""Initial schema with strict DRRM enums

Revision ID: ce311f188ab8
Revises: 
Create Date: 2026-08-27 10:54:28.847761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce311f188ab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='Viewer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            role IN (\n                'Viewer',\n                'Executive',\n                'Encoder',\n                'Validator',\n                'Operations Officer',\n                'Administrator'\n            )\n            ", name='ck_app_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_table('barangays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psgc_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('psgc_code')
    )
    op.create_table('response_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='Available', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resource_type IN ('Response Team', 'Vehicle', 'Equipment')", name='ck_response_resources_type'),
    sa.CheckConstraint("status IN ('Available', 'Assigned', 'Maintenance', 'Out of Service')", name='ck_response_resources_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_code', name='uq_response_resources_code')
    )
    op.create_table('system_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('actor_snapshot', sa.String(length=200), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation IN ('INSERT', 'UPDATE', 'DELETE')", name='ck_system_audit_log_operation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_audit_log_occurred_at', 'system_audit_log', ['occurred_at'], unique=False)
    op.create_index('ix_system_audit_log_table_name', 'system_audit_log', ['table_name'], unique=False)
    op.create_table('disaster_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.Column('hazard_category', sa.Enum('HYDROMETEOROLOGICAL', 'GEOLOGICAL', 'BIOLOGICAL', 'HUMAN_INDUCED', name='hazard_category_enum'), nullable=False),
    sa.Column('hazard_type', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('listo_cpa_level', sa.String(length=50), nullable=True),
    sa.Column('current_alert_level_id', sa.Integer(), nullable=False),
    sa.Column('eoc_status', sa.Enum('MONITORING', 'STANDBY', 'ACTIVE', name='eoc_status_enum'), nullable=False),
    sa.Column('current_sitrep_number', sa.String(length=30), nullable=True),
    sa.Column('official_reference', sa.String(length=255), nullable=True),
    sa.Column('situation_overview', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_alert_level_id'], ['alert_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disaster_events_current_alert_level_id'), 'disaster_events', ['current_alert_level_id'], unique=False)
    op.create_index('uq_disaster_events_one_active', 'disaster_events', ['is_active'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('evacuation_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('safe_capacity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('safe_capacity >= 0', name='ck_evacuation_centers_capacity'),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'barangay_id', name='uq_evacuation_centers_name_barangay')
    )
    op.create_index(op.f('ix_evacuation_centers_barangay_id'), 'evacuation_centers', ['barangay_id'], unique=False)
    op.create_table('alert_level_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('previous_alert_level_id', sa.Integer(), nullable=True),
    sa.Column('new_alert_level_id', sa.Integer(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authority_reference', sa.String(length=255), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['app_users.id'], name='fk_alert_level_history_changed_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_alert_level_id'], ['alert_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_alert_level_id'], ['alert_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_level_history_changed_by_user_id'), 'alert_level_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_alert_level_history_event_id'), 'alert_level_history', ['event_id'], unique=False)
    op.create_table('barangay_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supersedes_update_id', sa.Integer(), nullable=True),
    sa.Column('submission_key', sa.String(length=36), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.String(length=150), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=False),
    sa.Column('situation_status', sa.String(length=20), nullable=False),
    sa.Column('affected_families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('affected_individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inside_ec_families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inside_ec_individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outside_ec_families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outside_ec_individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('flood_status', sa.String(length=30), server_default='Unknown', nullable=False),
    sa.Column('flood_depth_cm', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('road_status', sa.String(length=50), server_default='Unknown', nullable=False),
    sa.Column('power_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('water_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('rescue_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('validation_status', sa.String(length=30), server_default='Submitted', nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=150), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            power_status IN (\n                'Unknown',\n                'Normal',\n                'Partial',\n                'Interrupted'\n            )\n            ", name='ck_barangay_updates_power_status'),
    sa.CheckConstraint("\n            road_status IN (\n                'Unknown',\n                'Passable',\n                'Passable to Large Vehicles Only',\n                'Limited Access',\n                'Impassable'\n            )\n            ", name='ck_barangay_updates_road_status'),
    sa.CheckConstraint("\n            situation_status IN (\n                'No Report',\n                'Normal',\n                'Monitoring',\n                'Affected',\n                'Critical'\n            )\n            ", name='ck_barangay_updates_situation_status'),
    sa.CheckConstraint("\n            validation_status IN (\n                'Draft',\n                'Submitted',\n                'For Validation',\n                'Validated',\n                'Needs Correction',\n                'Superseded'\n            )\n            ", name='ck_barangay_updates_validation_status'),
    sa.CheckConstraint("\n            water_status IN (\n                'Unknown',\n                'Normal',\n                'Partial',\n                'Interrupted'\n            )\n            ", name='ck_barangay_updates_water_status'),
    sa.CheckConstraint('\n            affected_families >= 0\n            AND affected_individuals >= 0\n            AND inside_ec_families >= 0\n            AND inside_ec_individuals >= 0\n            AND outside_ec_families >= 0\n            AND outside_ec_individuals >= 0\n            AND flood_depth_cm >= 0\n            AND rescue_requests >= 0\n            ', name='ck_barangay_updates_nonnegative_counts'),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['app_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['app_users.id'], name='fk_barangay_updates_submitted_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_update_id'], ['barangay_updates.id'], name='fk_barangay_updates_supersedes_update_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_key', name='uq_barangay_updates_submission_key')
    )
    op.create_index(op.f('ix_barangay_updates_barangay_id'), 'barangay_updates', ['barangay_id'], unique=False)
    op.create_index(op.f('ix_barangay_updates_event_id'), 'barangay_updates', ['event_id'], unique=False)
    op.create_index(op.f('ix_barangay_updates_recorded_at'), 'barangay_updates', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_barangay_updates_reviewed_by_user_id'), 'barangay_updates', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_barangay_updates_submitted_by_user_id'), 'barangay_updates', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_barangay_updates_supersedes_update_id'), 'barangay_updates', ['supersedes_update_id'], unique=False)
    op.create_table('cross_barangay_evacuation_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('evacuation_center_id', sa.Integer(), nullable=False),
    sa.Column('origin_barangay_id', sa.Integer(), nullable=False),
    sa.Column('submission_key', sa.String(length=36), nullable=True),
    sa.Column('families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.String(length=150), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('families >= 0 AND individuals >= 0 AND families <= individuals', name='ck_cross_barangay_allocation_counts'),
    sa.ForeignKeyConstraint(['evacuation_center_id'], ['evacuation_centers.id'], name='fk_cross_barangay_allocations_center_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], name='fk_cross_barangay_allocations_event_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_barangay_id'], ['barangays.id'], name='fk_cross_barangay_allocations_origin_barangay_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['app_users.id'], name='fk_cross_barangay_allocations_recorded_by_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_key', name='uq_cross_barangay_allocations_submission_key')
    )
    op.create_index('ix_cross_barangay_allocations_center_id', 'cross_barangay_evacuation_allocations', ['evacuation_center_id'], unique=False)
    op.create_index('ix_cross_barangay_allocations_event_id', 'cross_barangay_evacuation_allocations', ['event_id'], unique=False)
    op.create_index('ix_cross_barangay_allocations_origin_id', 'cross_barangay_evacuation_allocations', ['origin_barangay_id'], unique=False)
    op.create_index('ix_cross_barangay_allocations_recorded_at', 'cross_barangay_evacuation_allocations', ['recorded_at'], unique=False)
    op.create_index('ix_cross_barangay_allocations_recorded_by_user_id', 'cross_barangay_evacuation_allocations', ['recorded_by_user_id'], unique=False)
    op.create_table('evacuation_center_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supersedes_update_id', sa.Integer(), nullable=True),
    sa.Column('submission_key', sa.String(length=36), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.String(length=150), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('evacuation_center_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('families', sa.Integer(), server_default='0', nullable=False),
    sa.Column('individuals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('children', sa.Integer(), server_default='0', nullable=False),
    sa.Column('senior_citizens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pwd', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pregnant_women', sa.Integer(), server_default='0', nullable=False),
    sa.Column('medical_cases', sa.Integer(), server_default='0', nullable=False),
    sa.Column('food_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('water_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('electricity_status', sa.String(length=20), server_default='Unknown', nullable=False),
    sa.Column('sanitation_status', sa.String(length=50), server_default='Unknown', nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('validation_status', sa.String(length=30), server_default='Submitted', nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=150), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            electricity_status IN (\n                'Unknown',\n                'Available',\n                'Partial',\n                'Unavailable'\n            )\n            ", name='ck_evacuation_updates_electricity_status'),
    sa.CheckConstraint("\n            food_status IN (\n                'Unknown',\n                'Sufficient',\n                'Low',\n                'Critical',\n                'Unavailable'\n            )\n            ", name='ck_evacuation_updates_food_status'),
    sa.CheckConstraint("\n            status IN (\n                'Standby',\n                'Open',\n                'Full',\n                'Over Capacity',\n                'Closed'\n            )\n            ", name='ck_evacuation_updates_status'),
    sa.CheckConstraint("\n            validation_status IN (\n                'Draft',\n                'Submitted',\n                'For Validation',\n                'Validated',\n                'Needs Correction',\n                'Superseded'\n            )\n            ", name='ck_evacuation_updates_validation_status'),
    sa.CheckConstraint("\n            water_status IN (\n                'Unknown',\n                'Sufficient',\n                'Low',\n                'Critical',\n                'Unavailable'\n            )\n            ", name='ck_evacuation_updates_water_status'),
    sa.CheckConstraint('\n            families >= 0\n            AND individuals >= 0\n            AND children >= 0\n            AND senior_citizens >= 0\n            AND pwd >= 0\n            AND pregnant_women >= 0\n            AND medical_cases >= 0\n            ', name='ck_evacuation_updates_nonnegative_counts'),
    sa.ForeignKeyConstraint(['evacuation_center_id'], ['evacuation_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['app_users.id'], name='fk_evacuation_center_updates_reviewed_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['app_users.id'], name='fk_evacuation_center_updates_submitted_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_update_id'], ['evacuation_center_updates.id'], name='fk_evacuation_center_updates_supersedes_update_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_key', name='uq_evacuation_updates_submission_key')
    )
    op.create_index(op.f('ix_evacuation_center_updates_evacuation_center_id'), 'evacuation_center_updates', ['evacuation_center_id'], unique=False)
    op.create_index(op.f('ix_evacuation_center_updates_event_id'), 'evacuation_center_updates', ['event_id'], unique=False)
    op.create_index(op.f('ix_evacuation_center_updates_recorded_at'), 'evacuation_center_updates', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_evacuation_center_updates_reviewed_by_user_id'), 'evacuation_center_updates', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_evacuation_center_updates_submitted_by_user_id'), 'evacuation_center_updates', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_evacuation_center_updates_supersedes_update_id'), 'evacuation_center_updates', ['supersedes_update_id'], unique=False)
    op.create_table('event_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authority_reference', sa.String(length=255), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.String(length=150), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['app_users.id'], name='fk_event_change_history_changed_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], name='fk_event_change_history_event_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_change_history_changed_by_user_id'), 'event_change_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_event_change_history_effective_at'), 'event_change_history', ['effective_at'], unique=False)
    op.create_index(op.f('ix_event_change_history_event_id'), 'event_change_history', ['event_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_key', sa.String(length=36), nullable=True),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reported_by', sa.String(length=150), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('control_number', sa.String(length=40), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=False),
    sa.Column('exact_location', sa.String(length=255), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('persons_affected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='Reported', nullable=False),
    sa.Column('assigned_team', sa.String(length=150), nullable=True),
    sa.Column('assigned_vehicle', sa.String(length=100), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('validation_status', sa.String(length=30), server_default='Submitted', nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            priority IN (\n                'Low',\n                'Moderate',\n                'High',\n                'Critical'\n            )\n            ", name='ck_incidents_priority'),
    sa.CheckConstraint("\n            status IN (\n                'Reported',\n                'For Verification',\n                'Verified',\n                'Team Dispatched',\n                'Responding',\n                'Resolved',\n                'Cancelled'\n            )\n            ", name='ck_incidents_status'),
    sa.CheckConstraint("\n            validation_status IN (\n                'Draft',\n                'Submitted',\n                'For Validation',\n                'Validated',\n                'Needs Correction',\n                'Superseded'\n            )\n            ", name='ck_incidents_validation_status'),
    sa.CheckConstraint('persons_affected >= 0', name='ck_incidents_persons_affected'),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['app_users.id'], name='fk_incidents_reported_by_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'control_number', name='uq_incidents_event_control_number'),
    sa.UniqueConstraint('submission_key', name='uq_incidents_submission_key')
    )
    op.create_index(op.f('ix_incidents_barangay_id'), 'incidents', ['barangay_id'], unique=False)
    op.create_index(op.f('ix_incidents_event_id'), 'incidents', ['event_id'], unique=False)
    op.create_index(op.f('ix_incidents_reported_by_user_id'), 'incidents', ['reported_by_user_id'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('generation_key', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=40), server_default='Situation Report', nullable=False),
    sa.Column('report_mode', sa.String(length=40), nullable=False),
    sa.Column('sitrep_number', sa.String(length=30), nullable=True),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=150), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_mode IN ('Provisional Operational', 'Official Validated')", name='ck_report_snapshots_report_mode'),
    sa.CheckConstraint("report_type IN ('Situation Report')", name='ck_report_snapshots_report_type'),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], name='fk_report_snapshots_event_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['app_users.id'], name='fk_report_snapshots_generated_by_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_key', name='uq_report_snapshots_generation_key')
    )
    op.create_index('ix_report_snapshots_event_id', 'report_snapshots', ['event_id'], unique=False)
    op.create_index('ix_report_snapshots_generated_at', 'report_snapshots', ['generated_at'], unique=False)
    op.create_index('ix_report_snapshots_generated_by_user_id', 'report_snapshots', ['generated_by_user_id'], unique=False)
    op.create_table('incident_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.String(length=150), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['app_users.id'], name='fk_incident_history_changed_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_incident_history_incident_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_history_changed_by_user_id'), 'incident_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_incident_history_effective_at'), 'incident_history', ['effective_at'], unique=False)
    op.create_index(op.f('ix_incident_history_incident_id'), 'incident_history', ['incident_id'], unique=False)
    op.create_table('incident_resource_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.String(length=150), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['app_users.id'], name='fk_incident_resource_assignments_assigned_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_incident_resource_assignments_incident_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['response_resources.id'], name='fk_incident_resource_assignments_resource_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_resource_assignments_assigned_by_user_id'), 'incident_resource_assignments', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_incident_resource_assignments_incident_id'), 'incident_resource_assignments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_resource_assignments_resource_id'), 'incident_resource_assignments', ['resource_id'], unique=False)
    op.create_index('uq_active_incident_resource_assignment', 'incident_resource_assignments', ['resource_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_incident_resource_assignment', table_name='incident_resource_assignments', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index(op.f('ix_incident_resource_assignments_resource_id'), table_name='incident_resource_assignments')
    op.drop_index(op.f('ix_incident_resource_assignments_incident_id'), table_name='incident_resource_assignments')
    op.drop_index(op.f('ix_incident_resource_assignments_assigned_by_user_id'), table_name='incident_resource_assignments')
    op.drop_table('incident_resource_assignments')
    op.drop_index(op.f('ix_incident_history_incident_id'), table_name='incident_history')
    op.drop_index(op.f('ix_incident_history_effective_at'), table_name='incident_history')
    op.drop_index(op.f('ix_incident_history_changed_by_user_id'), table_name='incident_history')
    op.drop_table('incident_history')
    op.drop_index('ix_report_snapshots_generated_by_user_id', table_name='report_snapshots')
    op.drop_index('ix_report_snapshots_generated_at', table_name='report_snapshots')
    op.drop_index('ix_report_snapshots_event_id', table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_incidents_reported_by_user_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_event_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_barangay_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_event_change_history_event_id'), table_name='event_change_history')
    op.drop_index(op.f('ix_event_change_history_effective_at'), table_name='event_change_history')
    op.drop_index(op.f('ix_event_change_history_changed_by_user_id'), table_name='event_change_history')
    op.drop_table('event_change_history')
    op.drop_index(op.f('ix_evacuation_center_updates_supersedes_update_id'), table_name='evacuation_center_updates')
    op.drop_index(op.f('ix_evacuation_center_updates_submitted_by_user_id'), table_name='evacuation_center_updates')
    op.drop_index(op.f('ix_evacuation_center_updates_reviewed_by_user_id'), table_name='evacuation_center_updates')
    op.drop_index(op.f('ix_evacuation_center_updates_recorded_at'), table_name='evacuation_center_updates')
    op.drop_index(op.f('ix_evacuation_center_updates_event_id'), table_name='evacuation_center_updates')
    op.drop_index(op.f('ix_evacuation_center_updates_evacuation_center_id'), table_name='evacuation_center_updates')
    op.drop_table('evacuation_center_updates')
    op.drop_index('ix_cross_barangay_allocations_recorded_by_user_id', table_name='cross_barangay_evacuation_allocations')
    op.drop_index('ix_cross_barangay_allocations_recorded_at', table_name='cross_barangay_evacuation_allocations')
    op.drop_index('ix_cross_barangay_allocations_origin_id', table_name='cross_barangay_evacuation_allocations')
    op.drop_index('ix_cross_barangay_allocations_event_id', table_name='cross_barangay_evacuation_allocations')
    op.drop_index('ix_cross_barangay_allocations_center_id', table_name='cross_barangay_evacuation_allocations')
    op.drop_table('cross_barangay_evacuation_allocations')
    op.drop_index(op.f('ix_barangay_updates_supersedes_update_id'), table_name='barangay_updates')
    op.drop_index(op.f('ix_barangay_updates_submitted_by_user_id'), table_name='barangay_updates')
    op.drop_index(op.f('ix_barangay_updates_reviewed_by_user_id'), table_name='barangay_updates')
    op.drop_index(op.f('ix_barangay_updates_recorded_at'), table_name='barangay_updates')
    op.drop_index(op.f('ix_barangay_updates_event_id'), table_name='barangay_updates')
    op.drop_index(op.f('ix_barangay_updates_barangay_id'), table_name='barangay_updates')
    op.drop_table('barangay_updates')
    op.drop_index(op.f('ix_alert_level_history_event_id'), table_name='alert_level_history')
    op.drop_index(op.f('ix_alert_level_history_changed_by_user_id'), table_name='alert_level_history')
    op.drop_table('alert_level_history')
    op.drop_index(op.f('ix_evacuation_centers_barangay_id'), table_name='evacuation_centers')
    op.drop_table('evacuation_centers')
    op.drop_index('uq_disaster_events_one_active', table_name='disaster_events', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_disaster_events_current_alert_level_id'), table_name='disaster_events')
    op.drop_table('disaster_events')
    op.drop_index('ix_system_audit_log_table_name', table_name='system_audit_log')
    op.drop_index('ix_system_audit_log_occurred_at', table_name='system_audit_log')
    op.drop_table('system_audit_log')
    op.drop_table('response_resources')
    op.drop_table('barangays')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_table('alert_levels')
    # ### end Alembic commands ###
