"""operational response incident resources and cross barangay allocation

Revision ID: d7b2f91e4c31
Revises: c2a14d5e8f20
Create Date: 2026-08-09
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d7b2f91e4c31"
down_revision: Union[str, Sequence[str], None] = "c2a14d5e8f20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "incidents",
        sa.Column(
            "submission_key",
            sa.String(length=36),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "reported_by_user_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "reported_by",
            sa.String(length=150),
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        "uq_incidents_submission_key",
        "incidents",
        ["submission_key"],
    )
    op.create_index(
        "ix_incidents_reported_by_user_id",
        "incidents",
        ["reported_by_user_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_incidents_reported_by_user_id",
        "incidents",
        "app_users",
        ["reported_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "incident_history",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "incident_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "change_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "field_name",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "previous_value",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "new_value",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "changed_by_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "changed_by",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "effective_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name="fk_incident_history_incident_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["app_users.id"],
            name="fk_incident_history_changed_by_user_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_incident_history_incident_id",
        "incident_history",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        "ix_incident_history_effective_at",
        "incident_history",
        ["effective_at"],
        unique=False,
    )
    op.create_index(
        "ix_incident_history_changed_by_user_id",
        "incident_history",
        ["changed_by_user_id"],
        unique=False,
    )

    op.create_table(
        "response_resources",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "resource_code",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "resource_type",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "subtype",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "details",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="Available",
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resource_type IN ('Response Team', 'Vehicle', 'Equipment')",
            name="ck_response_resources_type",
        ),
        sa.CheckConstraint(
            "status IN ('Available', 'Assigned', 'Maintenance', 'Out of Service')",
            name="ck_response_resources_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_code",
            name="uq_response_resources_code",
        ),
    )

    op.create_table(
        "incident_resource_assignments",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "incident_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "resource_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "assigned_by_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "assigned_by",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "released_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name="fk_incident_resource_assignments_incident_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["response_resources.id"],
            name="fk_incident_resource_assignments_resource_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["app_users.id"],
            name="fk_incident_resource_assignments_assigned_by_user_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_incident_resource_assignments_incident_id",
        "incident_resource_assignments",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        "ix_incident_resource_assignments_resource_id",
        "incident_resource_assignments",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        "ix_incident_resource_assignments_assigned_by_user_id",
        "incident_resource_assignments",
        ["assigned_by_user_id"],
        unique=False,
    )
    op.create_index(
        "uq_active_incident_resource_assignment",
        "incident_resource_assignments",
        ["resource_id"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
    )

    op.create_table(
        "cross_barangay_evacuation_allocations",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "event_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "evacuation_center_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "origin_barangay_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "submission_key",
            sa.String(length=36),
            nullable=True,
        ),
        sa.Column(
            "families",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "individuals",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "remarks",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "recorded_by_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "recorded_by",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "families >= 0 AND individuals >= 0 "
                "AND families <= individuals"
            ),
            name="ck_cross_barangay_allocation_counts",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["disaster_events.id"],
            name="fk_cross_barangay_allocations_event_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evacuation_center_id"],
            ["evacuation_centers.id"],
            name="fk_cross_barangay_allocations_center_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["origin_barangay_id"],
            ["barangays.id"],
            name="fk_cross_barangay_allocations_origin_barangay_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["app_users.id"],
            name="fk_cross_barangay_allocations_recorded_by_user_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "submission_key",
            name="uq_cross_barangay_allocations_submission_key",
        ),
    )
    op.create_index(
        "ix_cross_barangay_allocations_event_id",
        "cross_barangay_evacuation_allocations",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        "ix_cross_barangay_allocations_center_id",
        "cross_barangay_evacuation_allocations",
        ["evacuation_center_id"],
        unique=False,
    )
    op.create_index(
        "ix_cross_barangay_allocations_origin_id",
        "cross_barangay_evacuation_allocations",
        ["origin_barangay_id"],
        unique=False,
    )
    op.create_index(
        "ix_cross_barangay_allocations_recorded_by_user_id",
        "cross_barangay_evacuation_allocations",
        ["recorded_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_cross_barangay_allocations_recorded_at",
        "cross_barangay_evacuation_allocations",
        ["recorded_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_cross_barangay_allocations_recorded_at",
        table_name="cross_barangay_evacuation_allocations",
    )
    op.drop_index(
        "ix_cross_barangay_allocations_recorded_by_user_id",
        table_name="cross_barangay_evacuation_allocations",
    )
    op.drop_index(
        "ix_cross_barangay_allocations_origin_id",
        table_name="cross_barangay_evacuation_allocations",
    )
    op.drop_index(
        "ix_cross_barangay_allocations_center_id",
        table_name="cross_barangay_evacuation_allocations",
    )
    op.drop_index(
        "ix_cross_barangay_allocations_event_id",
        table_name="cross_barangay_evacuation_allocations",
    )
    op.drop_table(
        "cross_barangay_evacuation_allocations"
    )

    op.drop_index(
        "uq_active_incident_resource_assignment",
        table_name="incident_resource_assignments",
    )
    op.drop_index(
        "ix_incident_resource_assignments_assigned_by_user_id",
        table_name="incident_resource_assignments",
    )
    op.drop_index(
        "ix_incident_resource_assignments_resource_id",
        table_name="incident_resource_assignments",
    )
    op.drop_index(
        "ix_incident_resource_assignments_incident_id",
        table_name="incident_resource_assignments",
    )
    op.drop_table(
        "incident_resource_assignments"
    )
    op.drop_table(
        "response_resources"
    )

    op.drop_index(
        "ix_incident_history_changed_by_user_id",
        table_name="incident_history",
    )
    op.drop_index(
        "ix_incident_history_effective_at",
        table_name="incident_history",
    )
    op.drop_index(
        "ix_incident_history_incident_id",
        table_name="incident_history",
    )
    op.drop_table(
        "incident_history"
    )

    op.drop_constraint(
        "fk_incidents_reported_by_user_id",
        "incidents",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_incidents_reported_by_user_id",
        table_name="incidents",
    )
    op.drop_constraint(
        "uq_incidents_submission_key",
        "incidents",
        type_="unique",
    )
    op.drop_column(
        "incidents",
        "reported_by",
    )
    op.drop_column(
        "incidents",
        "reported_by_user_id",
    )
    op.drop_column(
        "incidents",
        "submission_key",
    )
