"""add barangay validation audit fields

Revision ID: f3eb0ea185ab
Revises: c81ff3be60f6
Create Date: 2026-08-06 12:32:56.528793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3eb0ea185ab'
down_revision: Union[str, Sequence[str], None] = 'c81ff3be60f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barangay_updates', sa.Column('reviewed_by', sa.String(length=150), nullable=True))
    op.add_column('barangay_updates', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('barangay_updates', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barangay_updates', 'reviewed_at')
    op.drop_column('barangay_updates', 'review_notes')
    op.drop_column('barangay_updates', 'reviewed_by')
    # ### end Alembic commands ###
